name: Auto merge
on:
  workflow_dispatch:
  pull_request_target:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: set-result
        with:
          script: console.log(JSON.stringify(context,null,2))
          result-encoding: string
      - name: Merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
          token: ${{ secrets.PERSONAL_TOKEN }}
